dist: trusty
language: node_js
node_js:
  - "8"
env:
  global:
  - GH_USER="cvakiitho"
  - GH_EMAIL="tomas.hartmann@sap.com"
  - REPO="openui5-suite"
  - GH_REPO="github.com/${GH_USER}/${REPO}.git"
script:
    #here shall be some test
after_success:
  - git remote
  - git config user.email ${GH_EMAIL}
  - git config user.name ${GH_USER}
  - git checkout master
  - git push "https://${GITHUB_PRIVATE_TOKEN}@${GH_REPO}" master > /dev/null 2>&1
